# Generated by Django 2.0.3 on 2018-12-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightedtext',
            name='start_of_selection',
            field=models.IntegerField(blank=True, null=True, verbose_name='start_of_selection'),
        ),
    ]
