# Generated by Django 2.0.3 on 2018-11-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttags',
            name='color',
            field=models.CharField(default='ff0000', max_length=7, verbose_name='color'),
            preserve_default=False,
        ),
    ]
