# Generated by Django 2.0.3 on 2018-12-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_documenttags_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightedtext',
            name='selected_text',
            field=models.TextField(verbose_name='selected_text'),
        ),
    ]
