# Generated by Django 2.0.3 on 2018-12-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20181201_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocuments',
            name='html_text',
            field=models.TextField(null=True, verbose_name='html_text'),
        ),
    ]
