# Generated by Django 2.0.3 on 2018-12-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_pdfdocuments_html_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocuments',
            name='html_text_created',
            field=models.BooleanField(default=False, verbose_name='html_text_created'),
        ),
    ]
