# Generated by Django 2.0.3 on 2018-11-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20181126_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_documents',
            name='html_created',
            field=models.BooleanField(default=False, verbose_name='html_created'),
        ),
        migrations.AddField(
            model_name='pdf_documents',
            name='text_created',
            field=models.BooleanField(default=False, verbose_name='html_created'),
        ),
        migrations.AddField(
            model_name='pdf_documents',
            name='text_document',
            field=models.TextField(null=True, verbose_name='text_document'),
        ),
        migrations.AlterField(
            model_name='highlighted_text',
            name='selected_text',
            field=models.CharField(max_length=1000, verbose_name='selected_text'),
        ),
        migrations.AlterField(
            model_name='pdf_documents',
            name='report',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
